{
 "title": "try-go-kit",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "go_gc_duration_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds" }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "samples" }
   ]
  },
  {
   "title": "go_memstats_gc_sys_bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_memstats_gc_sys_bytes", "legendFormat": "active_appenders" }
   ]
  },
  {
   "title": "http_request_duration_microseconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_microseconds"
    }
   ]
  },
  {
   "title": "http_requests_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "http_requests_total" }
   ]
  },
  {
   "title": "request_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "request_count" }
   ]
  },
  {
   "title": "request_latency_microseconds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "request_latency_microseconds" }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk(5, max(scrape_duration_seconds) by (job))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "created_id",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "created_id" }
   ]
  }
 ]
}